// create base on http://www.dailyfx.com/forex_forum/coding-strategy-advisors-indicators-functions/237563-ttm-squeeze-indicator.html
study("MTS") 
length = input(title="Length", type=integer, defval=20, minval=0) 
reverse = input(title="Inverse Chart ", type=bool, defval=false) 
bband(length, mult) =>
	sma(close, length) + mult * stdev(close, length)
keltner(length, mult) =>
	ema(close, length) + mult * ema(tr, length)

e1 = (highest(high, length) + lowest(low, length)) / 2 + sma(close, length)
osc_value = linreg(close - e1 / 2, length, 0)
osc = reverse ? osc_value * -1 : osc_value

diff_value = bband(length, 2) - keltner(length, 1)
diff = reverse ? diff_value * -1 : diff_value

osc_color = osc[1] < osc[0] ? osc[0] >= 0 ? #00ffff : #cc00cc : osc[0] >= 0 ? #009b9b : #ff9bff
mid_color = diff >= 0 ? green : red

plot(osc, color=osc_color, style=histogram, linewidth=2)
plot(0, color=mid_color, style=circles, linewidth=3)
