//@version=4
study("MCI", overlay=true, max_bars_back=900)

src = close
sma_type = "sma"
ema_type = "ema"
incompletecandles = input(true, title="Include current unclosed current candle")
bar = incompletecandles ? 0 : 1
forecast_src = src[bar]

matype(_src, _len, _type) =>
    sma_1 = sma(_src, _len)
    ema_1 = ema(_src, _len)
    _len == 0 ? _src : (_type == "sma" ? sma_1 : ema_1)

//###################Simple Moving Average#####################
showMA = input(false, title="Show Moving Averages")

ma_1_len = input(10, title="1. Moving Average", type=input.integer)
ma_2_len = input(20, title="2. Moving Average", type=input.integer)
ma_3_len = input(50, title="3. Moving Average", type=input.integer)
ma_4_len = input(100, title="4. Moving Average", type=input.integer)
ma_5_len = input(200, title="5. Moving Average", type=input.integer)

ma_1_col = color.red
ma_2_col = color.white
ma_3_col = color.blue
ma_4_col = color.purple
ma_5_col = color.green

ma_1 = showMA ? matype(forecast_src, ma_1_len, sma_type) : na
ma_2 = showMA ? matype(forecast_src, ma_2_len, sma_type) : na
ma_3 = showMA ? matype(forecast_src, ma_3_len, sma_type) : na
ma_4 = showMA ? matype(forecast_src, ma_4_len, sma_type) : na
ma_5 = showMA ? matype(forecast_src, ma_5_len, sma_type) : na

plot(ma_1, color=ma_1_col, linewidth=1, offset=-1 * bar, title="1. Moving Average")
plot(ma_2, color=ma_2_col, linewidth=1, offset=-1 * bar, title="2. Moving Average")
plot(ma_3, color=ma_3_col, linewidth=1, offset=-1 * bar, title="3. Moving Average")
plot(ma_4, color=ma_4_col, linewidth=1, offset=-1 * bar, title="4. Moving Average")
plot(ma_5, color=ma_5_col, linewidth=1, offset=-1 * bar, title="5. Moving Average")