//@version=4
study("MCI", overlay=true, max_bars_back=900)

src = close
sma_type = "sma"
ema_type = "ema"
incompletecandles = input(true, title="Include current unclosed current candle")
bar = incompletecandles ? 0 : 1
forecast_src = src[bar]

matype(_src, _len, _type) =>
    sma_1 = sma(_src, _len)
    ema_1 = ema(_src, _len)
    _len == 0 ? _src : (_type == "sma" ? sma_1 : ema_1)
    
//########################### TD Sequential ########################################
showTDSequential = input(false, "Show TD Sequential")
showSetup = input(true, "Show setup")
showCountdown = input(true, "Show countdown")
showPerfect = input(true, "Show perfect counts")
invertColours = input(false, "Invert colours")
showOnlyCompletion = input(false, "Only show completions")
showTDST = input(true, "Show TDST Support and Resistance")
setupRecyclesOnNextBar = input(true, "Setup recycles on next bar")
flip = input(false, "Setup commences after TD Price Flip")
showRisk = input(true, "Show risk line")
volatilitySmoothing = input(false, "Volatility smoothing (relaxed setup)")

shortColour = invertColours ? color.red : color.green
longColour = invertColours ? color.green : color.red
smoothedColour = color.black

setupShort = int(na)
setupLong = int(na)
setupCount = int(na)
setupColour = color(na)
perfectSetup = bool(na)

setupShort := if close < close[4] and (not volatilitySmoothing or close < close[5])
    0
else
    if flip
        if nz(setupShort[1]) == 0 and close[1] < close[5] and close > close[4]
            1
        else
            if nz(setupShort[1]) == 0
                0
            else
                nz(setupShort[1] + 1)
    else
        if setupShort[1] == 9
            setupRecyclesOnNextBar ? 1 : 0
        else
            nz(setupShort[1] + 1)

setupLong := if close > close[4] and (not volatilitySmoothing or close > close[5])
    0
else
    if flip
        if nz(setupLong[1]) == 0 and close[1] > close[5] and close < close[4]
            1
        else
            if nz(setupLong[1]) == 0
                0
            else
                nz(setupLong[1] + 1)
    else
        if setupLong[1] == 9
            setupRecyclesOnNextBar ? 1 : 0
        else
            nz(setupLong[1] + 1)

setupCount := max(setupShort, setupLong)
//setupColour := setupShort > 0 ? (setupLong > 0 ? smoothedColour : (setupCount == 8 or setupCount == 9 ? longColour : shortColour)) : (setupCount == 8 or setupCount == 9 ?  shortColour : longColour)

setupColour := setupShort > 0 ? setupLong > 0 ? smoothedColour : shortColour : longColour

perfectSetup := showPerfect and (setupShort == 8 and high >= high[1] and high >= high[2] or 
   setupShort == 9 and high >= high[2] and high >= high[3] or 
   setupLong == 8 and low <= low[1] and low <= low[2] or 
   setupLong == 9 and low <= low[2] and low <= low[3])


plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 1, title="Setup 1", char="1", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 2, title="Setup 2", char="2", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 3, title="Setup 3", char="3", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 4, title="Setup 4", char="4", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 5, title="Setup 5", char="5", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 6, title="Setup 6", char="6", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and showSetup and (not showOnlyCompletion or barstate.islast) and setupCount == 7, title="Setup 7", char="7", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and not perfectSetup and (not showOnlyCompletion or barstate.islast) and showSetup and setupCount == 8, title="Setup 8", char="8", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and not perfectSetup and showSetup and setupCount == 9, title="Setup 9", char="9", color=setupColour, transp=0, editable=false)

plotchar(showTDSequential and perfectSetup and showSetup and setupCount == 8, title="Perfect setup 8", char="➑", color=setupColour, transp=0, editable=false)
plotchar(showTDSequential and perfectSetup and showSetup and setupCount == 9, title="Perfect setup 9", char="➒", color=setupColour, transp=0, editable=false)


cdownShort = int(na)
cdownLong = int(na)
cdownColour = color(na)
cdownCount = int(na)
perfect8 = float(na)
perfectCountdown = bool(na)
lastCompletedSetup = int(na)
setupHigh = float(na)
setupLow = float(na)
cancelCountdown = bool(na)
recycleCountdown = bool(na)
LONG = -1
SHORT = 1
CANCELLED = 0

recycleCountdown := if setupShort == 9 and lastCompletedSetup[1] == SHORT or setupLong == 9 and lastCompletedSetup[1] == LONG
    highest(9) - lowest(9) >= setupHigh[1] - setupLow[1] and 
       (setupHigh[1] - setupLow[1]) * 1.618 > highest(9) - lowest(9)

highest_1 = highest(9)
setupHigh := recycleCountdown or setupShort == 9 and lastCompletedSetup[1] != SHORT or 
   setupLong == 9 and lastCompletedSetup[1] != LONG ? highest_1 : setupHigh[1]
lowest_1 = lowest(9)
setupLow := recycleCountdown or setupShort == 9 and lastCompletedSetup[1] != SHORT or 
   setupLong == 9 and lastCompletedSetup[1] != LONG ? lowest_1 : setupLow[1]

cancelCountdown := lastCompletedSetup[1] == SHORT and high < setupLow or 
   lastCompletedSetup[1] == LONG and low > setupHigh or recycleCountdown

lastCompletedSetup := setupLong == 9 ? LONG : 
   setupShort == 9 ? SHORT : cdownShort[1] == 13 and setupShort[1] != 9 or 
   cdownLong[1] == 13 and setupLong[1] != 9 or cancelCountdown ? CANCELLED : 
   lastCompletedSetup[1]

cdownShort := lastCompletedSetup != SHORT or cancelCountdown ? 0 : 
   close >= high[2] ? nz(cdownShort[1]) % 13 + 1 : nz(cdownShort[1]) % 13
cdownLong := lastCompletedSetup != LONG or cancelCountdown ? 0 : 
   close <= low[2] ? nz(cdownLong[1]) % 13 + 1 : nz(cdownLong[1]) % 13

cdownCount := max(cdownShort, cdownLong)
cdownColour := cdownShort > 0 ? shortColour : longColour

perfect8 := cdownCount < 8 ? na : cdownCount == 8 ? close : perfect8[1]
perfectCountdown := showPerfect and 
   (cdownShort == 13 and high >= perfect8 or cdownLong and low <= perfect8)

//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 1 and cdownCount[1] != 1, title="Countdown 1", char="", text="1", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 2 and cdownCount[1] == 1, title="Countdown 2", char="", text="2", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 3 and cdownCount[1] == 2, title="Countdown 3", char="", text="3", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 4 and cdownCount[1] == 3, title="Countdown 4", char="", text="4", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 5 and cdownCount[1] == 4, title="Countdown 5", char="", text="5", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 6 and cdownCount[1] == 5, title="Countdown 6", char="", text="6", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 7 and cdownCount[1] == 6, title="Countdown 7", char="", text="7", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 8 and cdownCount[1] == 7, title="Countdown 8", char="", text="8", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 9 and cdownCount[1] == 8, title="Countdown 9", char="", text="9", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 10 and cdownCount[1] == 9, title="Countdown 10", char="", text="10", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 11 and cdownCount[1] == 10, title="Countdown 11", char="", text="11", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
//plotchar(showTDSequential and showCountdown and (not showOnlyCompletion or barstate.islast) and cdownCount == 12 and cdownCount[1] == 11, title="Countdown 12", char="", text="12", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
plotchar(showTDSequential and not perfectCountdown and showCountdown and cdownCount == 13 and cdownCount[1] == 12, title="Countdown 13", char="", text="13", location=location.belowbar, textcolor=cdownColour, transp=0, editable=false)
plotchar(showTDSequential and perfectCountdown and showCountdown and cdownCount == 13 and cdownCount[1] == 12, title="Perfect Countdown 13", char="⓭", location=location.belowbar, color=cdownColour, transp=0, editable=false)

//plotshape(showTDSequential and showCountdown and cancelCountdown, title="Countdown broke setup support/resistance", location=location.belowbar, style=shape.xcross, color=cdownColour, transp=0, editable=false)

tdstSupport = float(na)
tdstResistance = float(na)
tdRisk = float(na)
riskbar = int(na)

highest_2 = highest(9)
tdstResistance := not showTDSequential or not showTDST ? na : setupLong == 9 ? highest_2 : close > tdstResistance[1] ? na : tdstResistance[1]
lowest_2 = lowest(9)
tdstSupport := not showTDSequential or not showTDST ? na : setupShort == 9 ? lowest_2 : close < tdstSupport[1] ? na : tdstSupport[1]

//alertcondition(close > tdstResistance[1] or close < tdstSupport[1], title="Close outside TDST range", message="Close outside TDST range")

plot(tdstResistance, title="TDST Resistance", color=longColour, style=plot.style_circles, linewidth=2)
plot(tdstSupport, title="TDST Support", color=shortColour, style=plot.style_circles, linewidth=2)

if not showTDSequential or not showRisk
    tdRisk := na
    tdRisk
else
    if setupLong == 9
        riskbar := -1 * lowestbars(9)[0]
        tdRisk := low[riskbar] - tr[riskbar]
        tdRisk
    else
        if setupShort == 9
            riskbar = -1 * highestbars(9)[0]
            tdRisk := high[riskbar] + tr[riskbar]
            tdRisk
        else
            tdRisk := min(open, close) < tdRisk[1] and max(open, close) > tdRisk[1] ? na : tdRisk[1]
            tdRisk

plot(tdRisk, title="TD Risk", color=color.blue, style=plot.style_circles, linewidth=1)