//@version=4
study(shorttitle = "TTS", title="Trend Trading System", overlay=false)

src = close
ema_length = input(26) 
ema_val = ema(low, ema_length)
vwap_length = input(13) 
vwap_val = ema(vwap, vwap_length)

len = input(14, minval=1, title="Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))

plot(rsi, color=color.white)
change1 = rsi > 60 ? color.green :na
change2 = rsi < 40 ? color.red: na
p1 = plot(rsi, style=plot.style_linebr, linewidth=2, color=change1)
p2 = plot(rsi, style=plot.style_linebr, linewidth=2, color=change2)
band1 = hline(70)
band2 = hline(30)
band3 = hline(55)
band4 = hline (45)
midline = hline (50)

fill(band1, band3, color=color.green, transp=90)
fill(band2, band4, color=color.red, transp=90)
fill(band3, band4, color=color.blue, transp=90)

//###########
//up trend buy and buy pullback
green_cond = (rsi > 55 and close > ema_val) ? 1 : 0
barcolor(green_cond ? color.green : na) 

orange_cond = (rsi > 50 and close > ema_val) ? 1 : 0
barcolor(orange_cond ? color.teal : na)
//###########

//###########
//down trend buy and buy pullback
red_cond = (rsi < 45 and close < ema_val) ? 1 : 0
barcolor(red_cond ? color.red : na) 

purple_cond = (rsi < 50 and close < ema_val) ? 1 : 0
barcolor(purple_cond ? color.orange : na)
//###########

//###########
//Exit Completely: In an uptrend, close your entire position on bars colored blue or red. (Again, closed bars)
//Exit Completely: In a downtrend, close your entire position on bars colored orange or green.

blue_cond = (rsi < 50 and close > ema_val) or (rsi > 50 and close < ema_val) ? 1 : 0
barcolor(blue_cond ? color.navy : na)

buy_pullback = (rsi > 50 and close < vwap_val) ? 1 : na
plotshape(buy_pullback, title="Buy Pullback", location=location.top, offset=0, style=shape.circle,color=color.lime, transp=0)

sell_pullback = (rsi < 50 and close > vwap_val) ? 1 : na
plotshape(sell_pullback, title="Sell Pullback", location=location.bottom, offset=0, style=shape.circle, color=color.red, transp=0)

buy = (rsi > 50 and close < vwap_val) ? 1 : na
plotshape(buy, style=shape.triangleup, location=location.bottom, color=color.lime, transp=0, offset=0)

sell = (rsi < 50 and close > vwap_val) ? 1 : na
plotshape(sell, style=shape.triangledown, location=location.top, color=color.red, transp=0, offset=0)

buy_setup_take_profits = (rsi > 75 and close > ema_val) ? 1 : na
plotchar(buy_setup_take_profits, title="Buy Setup Take Profits", location=location.top, offset=0, char='TP', color=color.orange, transp=0)

sell_setup_take_profits = rsi < 25 and close < ema_val ? rsi-5 : na
plotchar(sell_setup_take_profits, title="Sell Setup Take Profits", location=location.bottom, offset=0, char='TP', color=color.orange, transp=0)